### ISSUE TITLE
markdown as primary format

### ISSUE THREAD

**Issue by beresmate** [tiborsaas/iknowcode#1]
Could we move the whole thing to a markdown file, and add a script (gulp, grunt, whatever) to compile it to html if needed? Would be easier to read it on GH without cloning and opening in a browser.

**Comment by tiborsaas** [comment]
I'd like to keep it as HTML, the markup will evolve, because I intend to add design and more features.

**Comment by sergiks** [comment]
Upvote for Markdown. This makes the content accessible right on github. 
Poor UX in favor of some vague future plans is officially discouraged by this humble comment.

**Comment by tiborsaas** [comment]
I'd like to create a site like superherojs.com I can still generate the content from .md files. I'll have to research how to compile it. @beresmate any idea?

**Comment by beresmate** [comment]
Just search npm for it:

http://domchristie.github.io/to-markdown/
https://www.npmjs.com/package/markdown-to-html

You could compile from markdown -> html, or vica versa, your decision :)
